[build]
  publish = "dist" # This is where Vite will output the built files
  command = "npm run build" # Command to build your Vite project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
